name: actor-critic
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - h5py
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - ffmpeg
  - pip:
    - ipykernel
  - pyyaml
